import test from 'node:test';
import assert from 'node:assert/strict';
import { access, readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

async function loadPortfolio() {
  const dataUrl = pathToFileURL(path.join(root, 'src/data/portfolio.js')).href;
  return (await import(`${dataUrl}?test=${Date.now()}`)).portfolio;
}
const readText = (relativePath) => readFile(path.join(root, relativePath), 'utf8');

async function collectTextFiles(relativePath) {
  const entries = await readdir(path.join(root, relativePath), { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const item = path.join(relativePath, entry.name);
    if (entry.isDirectory()) files.push(...await collectTextFiles(item));
    else if (/\.(?:astro|html|js|mjs|css|xml|txt|md)$/.test(entry.name)) files.push(item);
  }
  return files;
}

test('portfolio data uses the approved truthful positioning and employment dates', async () => {
  const portfolio = await loadPortfolio();
  assert.equal(portfolio.positioning, 'AdTech Solutions Engineer · Technical Solutions Consultant');
  assert.equal(portfolio.experience[0].title, 'AdTech Solutions Engineer (Technical Solutions Consultant)');
  assert.equal(portfolio.experience[0].dates, '04/2025 — 07/2026');
  assert.equal(portfolio.experience[1].title, 'Cloud Solution Architect');
  assert.equal(portfolio.experience[1].dates, '08/2022 — 03/2025');
});

test('portfolio data exposes recruiter and shipped-project links', async () => {
  const portfolio = await loadPortfolio();
  const project = portfolio.projects.find((item) => item.slug === 'knowledge-nebula');
  assert.equal(portfolio.resumeUrl, '/Chris-Johnson-Resume.pdf');
  assert.equal(portfolio.contact.emailUrl, 'mailto:Chrismjohnson19@gmail.com');
  assert.equal(portfolio.contact.linkedinUrl, 'https://linkedin.com/in/christopherjohnson98');
  assert.equal(project.caseStudyUrl, '/work/knowledge-nebula/');
  assert.equal(project.liveUrl, 'https://document-graph-explorer.vercel.app');
  assert.equal(project.repoUrl, 'https://github.com/chrisatom1998/document-graph-explorer');
});

test('public web source excludes stale employment language, unsupported claims, and phone links', async () => {
  const files = [];
  for (const scanRoot of ['src', 'public', 'scripts', 'work']) files.push(...await collectTextFiles(scanRoot));
  files.push('index.html', 'styles.css', 'site.js', 'robots.txt', 'sitemap.xml');
  const banned = ['tel:', '678-642-6551', 'Solutions Architect · Google', '04/2025 — present', '04/2025 - Present', 'platform adoption twofold', 'upward of 35%', '45 publisher-oriented solutions'];
  for (const relativePath of files) {
    const contents = await readText(relativePath);
    for (const phrase of banned) assert.equal(contents.includes(phrase), false, `${relativePath} contains banned phrase: ${phrase}`);
  }
});

test('generated home page contains all primary conversion links', async () => {
  const home = await readText('index.html');
  const expectedLinks = ['/Chris-Johnson-Resume.pdf', 'mailto:Chrismjohnson19@gmail.com', 'https://linkedin.com/in/christopherjohnson98', '/work/knowledge-nebula/', 'https://document-graph-explorer.vercel.app', 'https://github.com/chrisatom1998/document-graph-explorer'];
  for (const link of expectedLinks) assert.ok(home.includes(link), `home page is missing ${link}`);
  assert.match(home, /Generated by scripts\/generate-static-fallback\.mjs/);
});

test('mobile hero headline stays compact enough to preserve the first screen', async () => {
  const styles = await readText('public/styles.css');
  assert.match(styles, /@media \(max-width:720px\).*?\.hero h1\{max-width:none;font-size:clamp\(2\.75rem,9vw,3\.5rem\)\}/s);
});

test('dedicated case study and discovery assets exist', async () => {
  const requiredFiles = ['work/knowledge-nebula/index.html', 'public/Chris-Johnson-Resume.pdf', 'public/assets/chris-johnson-og.png', 'public/assets/knowledge-nebula-orbit-transparent.webp', 'public/favicon.svg', 'public/CNAME', 'public/robots.txt', 'public/sitemap.xml', 'robots.txt', 'sitemap.xml'];
  for (const relativePath of requiredFiles) await assert.doesNotReject(access(path.join(root, relativePath)), `${relativePath} must exist`);
  const caseStudy = await readText('work/knowledge-nebula/index.html');
  assert.match(caseStudy, /Local-first architecture/);
  assert.match(caseStudy, /Why the edges are explainable/);
  assert.match(caseStudy, /SoftwareApplication/);
  const sitemap = await readText('sitemap.xml');
  assert.match(sitemap, /https:\/\/www\.chrisjohnson\.solutions\//);
  assert.match(sitemap, /https:\/\/www\.chrisjohnson\.solutions\/work\/knowledge-nebula\//);
});

test('project scripts and maintainer docs define the supported update flow', async () => {
  const packageJson = JSON.parse(await readText('package.json'));
  const readme = await readText('README.md');
  assert.equal(packageJson.engines.node, '>=22.12.0');
  assert.equal(packageJson.devDependencies.astro, '7.2.10');
  assert.equal(packageJson.scripts.test, 'node --test tests/*.test.mjs');
  assert.equal(packageJson.scripts['generate:fallback'], 'node scripts/generate-static-fallback.mjs');
  assert.match(readme, /src\/data\/portfolio\.js/);
  assert.match(readme, /npm run generate:fallback/);
  assert.match(readme, /Generated files/);
});

test('CI verifies pull requests and deploys successful main builds to GitHub Pages', async () => {
  const workflow = await readText('.github/workflows/pages.yml');
  assert.match(workflow, /pull_request:/);
  assert.match(workflow, /branches:\s*\[main\]/);
  assert.match(workflow, /node-version:\s*22\.12\.0/);
  assert.match(workflow, /npm install --no-audit --no-fund/);
  assert.match(workflow, /npm test/);
  assert.match(workflow, /npm run generate:fallback/);
  assert.match(workflow, /git diff --exit-code/);
  assert.match(workflow, /npm run build/);
  assert.match(workflow, /actions\/configure-pages@v5/);
  assert.match(workflow, /actions\/upload-pages-artifact@v3/);
  assert.match(workflow, /path:\s*\.\/dist/);
  assert.match(workflow, /actions\/deploy-pages@v4/);
  assert.match(workflow, /github\.event_name == 'push'/);
  assert.match(workflow, /github\.ref == 'refs\/heads\/main'/);
  assert.match(workflow, /pages:\s*write/);
  assert.match(workflow, /id-token:\s*write/);
});
